# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

#https://tabler.io/icons

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/JamieBriggsDev"

[social.params]
icon = "brand-github"

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://mastodon.social/@JBriggs_DEV"

[social.params]
icon = "brand-mastodon"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/jbriggs-dev/"

[social.params]
icon = "brand-linkedin"
